# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clapctl < Formula
  desc ""
  homepage "https://github.com/stdbio/autopilot"
  version "1.22.5"

  on_macos do
    url "https://github.com/stdbio/pkgs/releases/download/1.22.5/pkgs_1.22.5_darwin_all.tar.gz"
    sha256 "c36517fcd16814f31731c95a6a0b17d07749aa91d39956307b8d214c7a10ae73"

    def install
      bin.install "clapctl"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stdbio/pkgs/releases/download/1.22.5/pkgs_1.22.5_linux_arm64.tar.gz"
      sha256 "d41f77b579f6791729118654e47851cc3337e9996d7c042dd5436f30ebf4eb28"

      def install
        bin.install "clapctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stdbio/pkgs/releases/download/1.22.5/pkgs_1.22.5_linux_amd64.tar.gz"
      sha256 "c84c2f9ac82670f437da0c0343caf9a433144fd213e717100cf302089c20f696"

      def install
        bin.install "clapctl"
      end
    end
  end
end
